version: '3'

services:

  mysql:
    image: mysql/mysql-server:5.7
    restart: always
    env_file:
      - .env
    volumes:
      - ${APP_LOCATION}/.docker/data/mysql/:/var/lib/mysql
      - ${APP_LOCATION}/.docker/logs/mysql/:/var/log/mysql
    networks:
      - default
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      -  8080:80
    env_file:
      - .env
    environment:
      PMA_HOST: mysql
    container_name: presta_phpmyadmin

  app_dev:
    container_name: presta_app
    build:
      context: .
      args:
        APP_LOCATION: ${APP_LOCATION}
    command: >
      bash -c "cd /var/www/html/install 
      && php index_cli.php 
      --domain=${PS_DOMAIN} 
      --db_server=${MYSQL_SERVER} 
      --db_name=${MYSQL_DATABASE} 
      --db_user=${MYSQL_USER} 
      --db_password=${MYSQL_PASSWORD} 
      --email=${PS_ADMIN_EMAIL} 
      --password=${PS_ADMIN_PASSWORD} 
      --language=${PS_LANGUAGE} 
      --country=${PS_COUNTRY} 
      && apachectl -D FOREGROUND"
    volumes : 
      - ${APP_LOCATION}/:/var/www/html
    restart: always
    ports:
      - 8000:80
    depends_on: 
      - mysql
    env_file:
      - .env
    environment: 
      - _PS_MODE_DEV_=${PS_DEV_MODE}
    networks:
      - default
