version: "3"

services:
  mysql:
    image: mariadb:10.5.8
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3306:3306
    #--log-queries-not-using-indexes

  phpmyadmin:
    container_name: presta_${APP_NAME}_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    env_file:
      - .env
    environment:
      PMA_HOST: mysql

  app_dev:
    image: prestashop/prestashop:1.7-fpm
    container_name: presta_app
    #command: ["/tmp/wait-for-it.sh", "--timeout=60", "--strict", "db:3306", "--", "/tmp/run_install_prestashop.sh"]
    #volumes:
      #- ./sites/${APP_NAME}/app/:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - mysql
    environment:
      - DB_SERVER=${MYSQL_SERVER}
      - DB_PREFIX=ps161_
      - PS_DEV_MODE=${PS_DEV_MODE}
      - PS_INSTALL_AUTO=${PS_INSTALL_AUTO}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - PS_FOLDER_ADMIN=${PS_FOLDER_ADMIN}
      - PS_DOMAIN=${PS_DOMAIN}
      - PS_LANGUAGE=${PS_LANGUAGE}
      - PS_COUNTRY=${PS_COUNTRY}
      - PS_FOLDER_INSTALL=installed
