version: "3"

services:
  mysql:
    image: mariadb:10.5.8
    container_name: presta_${APP_NAME}_mysql
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      #- ./db_data/db/backup.sql:/docker-entrypoint-initdb.d/backup.sql #it loads an already existing database
      - ./sites/${APP_NAME}/data/mysql/:/var/lib/mysql
      - ./sites/${APP_NAME}/logs/mysql/:/var/log/mysql
    ports:
      - 3306:3306
    entrypoint: "" # On écrase l'entrypoint de l'image mysql : ENTRYPOINT ["docker-entrypoint.sh"]
    command: >
      bash -c "chown -R mysql:mysql /var/log/mysql 
      && exec /usr/local/bin/docker-entrypoint.sh mysqld 
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci 
      --log_error=/var/log/mysql/mysql_error.log 
      --general_log_file=/var/log/mysql/mysql.log --general_log=1 
      --slow_query_log_file=/var/log/mysql/mysql-slow.log --long_query_time=2 --slow_query_log=1"
    #--log-queries-not-using-indexes

  phpmyadmin:
    container_name: presta_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    env_file:
      - .env
    environment:
      PMA_HOST: mysql
  
  nginx:
    build: ./docker/nginx
    ports:
      - "8000:80"
      - "443"
    depends_on:
      - php-fpm
    volumes:
      - ./sites/${APP_NAME}/app/:/var/www/html/
      - ./logs/nginx/:/var/log/nginx
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    restart: always

  php-fpm:
    container_name: presta_${APP_NAME}_app
    build: 
      context: ./docker
      dockerfile: Dockerfile
      args:
        APP_NAME: ${APP_NAME}
        RUN_INSTALL: ${RUN_INSTALL}
    image: presta/${APP_NAME}_app:latest
    #command: ["/tmp/wait-for-it.sh", "--timeout=60", "--strict", "mysql:3306", "--", "/tmp/run_install_prestashop.sh", "${RUN_INSTALL}", "${APP_NAME}"]
    volumes:
      - ./sites/${APP_NAME}/app/:/var/www/html
      #- ~/.ssh/id_rsa:/root/.ssh/id_rsa
    expose:
      - 9000
    depends_on:
      - mysql
    env_file:
      - .env
